### ISSUE TITLE
Enable dark theme

### ISSUE THREAD

**Issue by Adarsh-K21** [Adarsh-K21/text-magic#1]

**Comment by ranaji038** [comment]
Sir, Please Assign me this issue

**Comment by ranaji038** [comment]
Sir, Please Assign me this issue

**Comment by Adarsh-K21** [comment]
assigned

**Comment by ranaji038** [comment]
![image](https://user-images.githubusercontent.com/90084352/195971784-1f528d8e-2f0d-45aa-a75f-bf8089e3ce4e.png)

**Comment by ranaji038** [comment]
Added the dark mode
