### ISSUE TITLE
Adding a functionality to find the "total occurrences of a word" entered by the user in text summary section

### ISSUE THREAD

**Issue by Divyanshu-jhaa** [Adarsh-K21/text-magic#14]
Also there is a bug in the Textform.js file (A variable has been declared twice so the whole site is down) So i will fix that also.

**Comment by akshat-kumar2109** [comment]
do we have to find the occurrence of a word in the string entered by user?
can you explain more what i have to do?

**Comment by Divyanshu-jhaa** [comment]
Actually I am also a contributor so I am just suggesting the maintainer of the repo this functionality and assign it to me.

**Comment by Adarsh-K21** [comment]
Assigned to you @Divyanshu-jhaa

**Comment by Adarsh-K21** [comment]
@akshat-kumar2109 you can also try to work on this enhancement
