### ISSUE TITLE
Text Copied after the text is copied 

### ISSUE THREAD

**Issue by Engineervinay** [Adarsh-K21/text-magic#16]
![Screenshot (64)](https://user-images.githubusercontent.com/29520476/195982743-b2510070-b984-4176-8ab9-1f397c212ba5.png)
as we can see here when we click on the 'copy text' button it's good to show the user that the text is copied. 
I would like to contribute to the project for hacktoberfest by adding the text copied feature after the text is copied.
Please Assign me this issue.

**Comment by Adarsh-K21** [comment]
We already have an alert for that. Contributed by @ayush-jain-09 and @iamrajkumar1. So I don't feel we need any enhancement in this.

Thanks
