### ISSUE TITLE
download as a text file

### ISSUE THREAD

**Issue by Engineervinay** [Adarsh-K21/text-magic#17]
I would like to add a new button that lets the user download the text in the textbox as a .txt file.
when the user clicks on the download button the text will be downloaded in txt format.
i would like to work on this issue please assign me this.

**Comment by Adarsh-K21** [comment]
Good enhancement idea. Assigned to you

**Comment by Engineervinay** [comment]
Thank You @Adarsh-K21  i'll start my work and create a PR
