### ISSUE TITLE
When the dark mode is enabled, change text to "Disable dark mode"

### ISSUE THREAD

**Issue by mnosov622** [Adarsh-K21/text-magic#6]
Hi!

If possible, could you assign this issue to me, please ?

**Comment by Adarsh-K21** [comment]
Assigned

**Comment by mnosov622** [comment]
Thank you!

**Comment by aritroo** [comment]
Hello @Adarsh-K21 
I want to work on this please assign me.

**Comment by developer208** [comment]
I already solved this issue @developer208

**Comment by Adarsh-K21** [comment]
thanks @mnosov622
